version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: '.next' 
post_build:
  commands:
    - echo Build completed on `date`
    - aws s3 cp --recursive .next/ s3://kimble.shop