version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source code dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm install -g serve
      - npx next export

artifacts:
  files:
    - '**/*'
  base-directory: 'out'
