version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - npm run export
artifacts:
  files:
    - '**/*'
  base-directory: out
